# Generated by Django 6.0.4 on 2026-04-23 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'queue',
                'ordering': ['-date'],
            },
        ),
    ]
