# Generated by Django 6.0.4 on 2026-06-03 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hard_block', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'block_reasons',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('seller_id', models.UUIDField()),
                ('json_before', models.JSONField(blank=True, null=True)),
                ('json_after', models.JSONField()),
                ('status', models.TextField(choices=[('MODERATED', 'Moderated'), ('IN_REVIEW', 'In Review'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked')])),
                ('kind', models.TextField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit')])),
                ('queue_priority', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_comment', models.TextField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('blocking_reasons', models.ManyToManyField(to='src.blockreason')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-updated_at', '-queue_priority'],
            },
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.ticket')),
            ],
            options={
                'db_table': 'field_reports',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=True, primary_key=True, serialize=False)),
                ('action', models.TextField(choices=[('CREATED', 'Created'), ('CLAIMED', 'Claimed'), ('RELEASED', 'Released'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked'), ('AUTO_RETURNED', 'Auto Returned')])),
                ('comment', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('moderation_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='src.ticket')),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-at'],
            },
        ),
    ]
