# Generated by Django 6.0.4 on 2026-06-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='moderator_comment',
            new_name='decision_comment',
        ),
    ]
