# Generated by Django 6.0.4 on 2026-06-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='blocking_history',
        ),
    ]
