# Generated by Django 6.0.4 on 2026-06-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_ticket_blocking_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='moderation_ricket',
            new_name='moderation_ticket',
        ),
    ]
