# Generated by Django 6.0.4 on 2026-04-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_blockreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='product_id',
            new_name='product',
        ),
    ]
