# Generated by Django 6.0.4 on 2026-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_moderator_comment_ticket_decision_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIdempotencyKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(editable=False)),
            ],
        ),
    ]
