# Generated by Django 6.0.4 on 2026-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['updated_at', 'queue_priority']},
        ),
        migrations.RenameField(
            model_name='fieldreport',
            old_name='field_name',
            new_name='field_path',
        ),
        migrations.RenameField(
            model_name='fieldreport',
            old_name='new_value',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='fieldreport',
            name='old_value',
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='severity',
            field=models.TextField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO'),
            preserve_default=False,
        ),
    ]
