# Generated by Django 6.0.4 on 2026-06-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['queue_priority', 'updated_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('MODERATED', 'Moderated'), ('APPROVED', 'Approved'), ('IN_REVIEW', 'In Review'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked')]),
        ),
    ]
